# Generated by Django 5.2.5 on 2025-08-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
